Changing demo host
cuenca-mx/stpmex-python pull request #115
Opened 2020-09-05 19:51 UTC by chiqeen03

STP changed their demo host.

Old host: https://demo.stpmex.com:7024/speidemows/rest
New host: https://demo.stpmex.com:7024/speiws/rest

2020-09-05 19:57 UTC, matin requested changes
Only one change and bump the maintenance version of the library

2020-09-05 19:57 UTC, matin commented on stpmex/client.py
> +DEMO_BASE_URL = f'{DEMO_HOST}/speiws/rest'
This is now redundant with `PROD_BASE_URL`. If the endpoints both both environments are the same, you should handle this differently

2020-09-05 19:59 UTC, matin commented
Rebase as well. 

While you're at it, you should incorporate the version changes proposed by dependabot

2020-09-05 20:01 UTC, matin commented
Take a look at https://github.com/cuenca-mx/stpmex-python/pull/108 on how to handle the account revision change. Not sure why it's still in draft, but we might as well resolve it

2020-09-05 20:02 UTC, matin commented
Bump the minor version since there's a breaking change from incorporating #118

2020-09-07 17:28 UTC, felipaoo requested changes

2020-09-07 17:28 UTC, felipaoo commented on stpmex/client.py
> +        ...
Agrega comentario de porque motivo no se hace ninguna acción en este caso.

2020-09-07 17:28 UTC, felipaoo commented on stpmex/client.py
> +                _raise_description_error_exc(resp)
cambiar código anidado por algo más plano, ej: https://github.com/cuenca-mx/stpmex-python/pull/108/files#diff-b23372b5bc04ed97bbf3529676496f80R115-R120

2020-09-07 20:47 UTC, felipaoo submitted a review, later dismissed
Please add `closes #` in the main comment

2020-09-21 16:10 UTC, felipaoo approved these changes

2020-09-21 16:38 UTC, merged