blocked transfers
cuenca-mx/stpmex-python pull request #155
Opened 2021-01-11 21:00 UTC by felipaoo

raises `BlockedInstitution` exception when `crear_orden` is called. closes #154

2021-01-11 22:31 UTC, matin requested changes

2021-01-11 22:31 UTC, matin commented on stpmex/resources/ordenes.py
> +    for item in os.environ.get('BLOCKED_INSTITUTIONS', '').split(',')
Hard-code it vs using an env var. There's only one

2021-01-11 23:04 UTC, felipaoo commented on stpmex/resources/ordenes.py
> +    for item in os.environ.get('BLOCKED_INSTITUTIONS', '').split(',')
ok, `90642` (Reforma)  also is blocked. It was like 6 months ago when Taurus used that institution

2021-01-13 02:54 UTC, felipaoo commented on stpmex/exc.py
> +class BlockedInstitution(StpmexException):
When `BlockedInstitution` inherit from `pydantic.errors.PydanticValueError` pydantic wraps it with `pydantic.error_wrappers.ValidationError` so original exception is lost. And the expected exception would be `ValidationError` instead of `BlockedInstitution`.

2021-01-13 03:30 UTC, matin commented on stpmex/exc.py
> +class BlockedInstitution(StpmexException):
That's the intended effect. That way, all validation errors are raised at the same time

2021-01-13 03:31 UTC, matin requested changes

2021-01-13 03:31 UTC, matin commented on stpmex/types.py
>      from pydantic.typing import CallableGenerator  # pragma: no cover
Take a look at the setup.cfg for cuenca-python for how to ignore this line in coverage in a cleaner way

2021-01-13 03:32 UTC, matin commented
Also missing the version bump

2021-01-13 16:15 UTC, matin requested changes

2021-01-13 16:15 UTC, matin commented on stpmex/types.py
> +# STP does not allow make tranfers to this banks codes.
This sentence is grammatically incorrect

2021-01-13 16:15 UTC, matin commented on tests/resources/test_ordenes.py
> +    with pytest.raises(ValidationError):
You should check that the specific error code exists amongst the errors

2021-01-13 16:15 UTC, matin commented on stpmex/exc.py
> +    msg_template = 'código de banco bloqueado'
More useful to say `f{bank_name} has been blocked by STP.'`

2021-01-13 19:17 UTC, matin commented on tests/resources/test_ordenes.py
> +        'msg': 'Asp Integra Opc has been blocked by STP.',
perfect!

2021-01-13 19:18 UTC, matin requested changes
you missed one of the comments

2021-01-13 19:18 UTC, matin commented on stpmex/types.py
>      from pydantic.typing import CallableGenerator  # pragma: no cover
you still haven't changed this. Here: https://github.com/cuenca-mx/cuenca-python/blob/main/setup.cfg#L23-L26

2021-01-13 19:20 UTC, matin commented on tests/resources/test_ordenes.py
> +    }
for consistency with our code style, this should be in the following style:
```python
dict(
    loc='xxx',
    msg='yyy,
)
```

2021-01-13 19:39 UTC, felipaoo commented
listo

2021-01-13 19:42 UTC, matin approved these changes

2021-01-13 19:42 UTC, merged

2021-01-13 19:43 UTC, matin commented
@felipaoo can you release?

2021-01-13 19:43 UTC, felipaoo commented
yes